apiVersion: v1
kind: Pod
metadata:
  name: atong-pvc-shell
spec:
  restartPolicy: Never
  containers:
    - name: shell
      image: ubuntu:22.04
      command: ["/bin/bash", "-c", "apt-get update && apt-get install -y python3 nano unzip && tail -f /dev/null"]
      resources:
        requests:
          cpu: "100m"
          memory: "1Gi"
          ephemeral-storage: 600Gi
        limits:
          cpu: "100m"
          memory: "1Gi"
          ephemeral-storage: 600Gi
      volumeMounts:
        - name: atong-spectre
          mountPath: /root/gurusmart
        - name: smart-datasets
          mountPath: /root/datasets
        - name: workspace
          mountPath: /workspace
  volumes:
    - name: atong-spectre
      persistentVolumeClaim:
        claimName: atong-spectre
    - name: smart-datasets
      persistentVolumeClaim:
        claimName: smart-datasets
    - name: workspace
      emptyDir: {}
